sudo: false
language: node_js

node_js:
- "5.1"

os:
  -osx
  -linux

install:
- npm install
- npm install -g vsce
- vsce package

deploy:
  provider: releases
  api_key:
    secure: u/fkBZvw3UWqyscS3O/McFiUb1YZ/lQMvBdIcIDONMcqJDLCNO6zixm5lAjBkhllqFicenALzrj2oVA4eVnX4Ydgw9PrzitmluZPO4TfuP6EAJd9he04z4Bf4T27pN6SRFCydLnXHvHaHKORswp1/Orzwba38CEhrsd7IvDHHwljZSCZGkKYV2qMiy5Zq3wEuCorqjNU9KhsPy4FzXVh5ZVVV5n+cg7SQ8YjJE9BfhpnWlekDvomeXd4MbW3ltnmMzzueoarCQSW8as53G82MqZgqloSHowf7w4RmuAJ2ufe+OHzKqSEyZKwmAsMymE8P1/y9lrlQXLxelhGnJ1R6UcHOf0JpKVDUap6IsxYnOH99qZ71W5WjzUj+JkV6Uk52JKjEskimWY3ciIser7Lal1OALaxJ0+YPJBV+SJLTwcjsFnHksinGFaHTcnQ30FKO+oZ3Id9efQNRWoBR8AI66qHuQn8ceslSuxPa6FMLiqLgmcNyJ8KW4sAO07m58w2hlDw9DGn7KFWvsDTsz0McOVNoB/b7MKBnD4ciYihZyz4QbMDi1Fe7ruIdIMg30cPOHkA2wGiOkcE92e0SlyzlzOfEGZ6GStQt8Xwd0mYS4ioM3CrY8iKheJvtLz6ht45e9gXv+hIRoS2V0WDPrnUesdGDgSodbp1Wz7KrAz4zZA=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: OmniSharp/omnisharp-vscode
    tags: true
